services:
  - type: web
    name: pharmaceutical-tracking-system
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: pharmaceutical-data
      mountPath: /app/data
      sizeGB: 1